//
// il2cpp_h.cpp — Generate Il2CppDumper-compatible il2cpp.h header file
//
// Phase 4: C struct definitions for all il2cpp types
//

#include "il2cpp_h.h"
#include "script_json.h"  // for fix_name, parse_type, il2cpp_base
#include "il2cpp-tabledefs.h"  // for FIELD_ATTRIBUTE_*

// il2cpp API function pointer extern declarations
// (same pattern as script_json.cpp — definitions come from il2cpp_dump.cpp or test stubs)
#define DO_API(r, n, p) extern r (*n) p
#include "il2cpp-api-functions.h"
#undef DO_API

// Logging — in test mode (SCRIPT_JSON_TEST), log.h is not available.
#ifndef SCRIPT_JSON_TEST
#include "log.h"
#else
#include <cstdio>
#define LOGI(...) do { printf("[INFO ] "); printf(__VA_ARGS__); printf("\n"); } while(0)
#define LOGE(...) do { fprintf(stderr, "[ERROR] "); fprintf(stderr, __VA_ARGS__); fprintf(stderr, "\n"); } while(0)
#endif

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <functional>
#include <sstream>
#include <set>
#include <map>

// ================================================================
// Generic header — base type definitions (from Il2CppDumper)
// ================================================================

static const char *kGenericHeader = R"(// Generated by Zygisk-Il2CppDumper
// https://github.com/Perfare/Il2CppDumper

#pragma once

#include <stdint.h>

typedef void (*Il2CppMethodPointer)();
typedef struct Il2CppType Il2CppType;
typedef struct Il2CppArrayBounds Il2CppArrayBounds;
typedef struct Il2CppObject Il2CppObject;
typedef struct Il2CppString Il2CppString;
typedef struct VirtualInvokeData VirtualInvokeData;
typedef struct Il2CppRGCTXData Il2CppRGCTXData;
typedef struct Il2CppRuntimeInterfaceOffsetPair Il2CppRuntimeInterfaceOffsetPair;

struct Il2CppArrayBounds {
    il2cpp_array_size_t length;
    int32_t lower_bound;
};

struct Il2CppObject {
    Il2CppClass *klass;
    void *monitor;
};

struct Il2CppString {
    Il2CppObject object;
    int32_t length;
    uint16_t chars[1];
};

struct VirtualInvokeData {
    Il2CppMethodPointer methodPtr;
    const MethodInfo* methodInfo;
};

struct Il2CppRGCTXData {
    union {
        const Il2CppType* type;
        const MethodInfo* method;
        Il2CppClass* klass;
    };
};

struct Il2CppRuntimeInterfaceOffsetPair {
    Il2CppClass* interfaceType;
    int32_t offset;
};

)";

// ================================================================
// Version-specific header — Il2CppClass layout
// ================================================================

static const char *kVersionHeader = R"(
typedef struct Il2CppClass_1 {
    const Il2CppImage* image;
    void* gc_desc;
    const char* name;
    const char* namespaze;
    Il2CppType byval_arg;
    Il2CppType this_arg;
    Il2CppClass* element_class;
    Il2CppClass* castClass;
    Il2CppClass* declaringType;
    Il2CppClass* parent;
    Il2CppClass* generic_class;
    Il2CppType* genericParameterConstraints;
    const Il2CppInteropData* interopData;
    Il2CppClass** nestedTypes;
    Il2CppClass** implementedInterfaces;
    Il2CppRuntimeInterfaceOffsetPair* interfaceOffsets;
    void* static_fields;
    const Il2CppRGCTXData* rgctx_data;
    void** typeHierarchy;
    uint32_t cctor_started_or_initialized_or_has_finalize;
    uint32_t initializationAttempted;
    uint32_t instance_size;
    uint32_t actualSize;
    uint32_t token;
    uint16_t flags;
    uint16_t tokenType;
    int16_t genericContainerIndex;
    int16_t customAttributeIndex;
    uint8_t instance_size_align;
    uint8_t naturalAligment;
    uint8_t packingSize;
    uint8_t bitflags1;
    uint8_t bitflags2;
    uint8_t method_count;
    uint8_t property_count;
    uint8_t field_count;
    uint8_t event_count;
    uint8_t nested_type_count;
    uint8_t vtable_count;
    uint8_t interfaces_count;
    uint8_t interface_offsets_count;
} Il2CppClass_1;

typedef struct Il2CppClass_2 {
    Il2CppMethodPointer* static_field_data;
    Il2CppMethodPointer* methodPointer;
    Il2CppMethodPointer* virtual_method_pointer;
    InvokerMethod* invoker_methods;
    Il2CppRuntimeInterfaceOffsetPair* interfaceOffsets;
    void* static_fields;
    const Il2CppType** genericArgumentOffsets;
    const Il2CppType** field_types;
    const Il2CppFieldInfo* fields;
    const Il2CppEventInfo* events;
    const Il2CppPropertyInfo* properties;
    const MethodInfo** methods;
    Il2CppClass** nestedTypes;
    Il2CppClass** implementedInterfaces;
    Il2CppVTable vtable;
} Il2CppClass_2;

struct Il2CppClass {
    Il2CppClass_1 _1;
    void* static_fields;
    const Il2CppRGCTXData* rgctx_data;
    Il2CppClass_2 _2;
};

)";

// ================================================================
// Runtime API — collect type info
// ================================================================

std::string get_field_type_name(const Il2CppType *type, bool *is_value_type, bool *is_custom_type) {
    *is_value_type = false;
    *is_custom_type = false;

    if (!type) {
        return "void";
    }

    auto type_val = type->type;

    switch (type_val) {
    case IL2CPP_TYPE_VOID:
        return "void";
    case IL2CPP_TYPE_BOOLEAN:
        return "bool";
    case IL2CPP_TYPE_CHAR:
        return "uint16_t";
    case IL2CPP_TYPE_I1:
        return "int8_t";
    case IL2CPP_TYPE_U1:
        return "uint8_t";
    case IL2CPP_TYPE_I2:
        return "int16_t";
    case IL2CPP_TYPE_U2:
        return "uint16_t";
    case IL2CPP_TYPE_I4:
        return "int32_t";
    case IL2CPP_TYPE_U4:
        return "uint32_t";
    case IL2CPP_TYPE_I8:
        return "int64_t";
    case IL2CPP_TYPE_U8:
        return "uint64_t";
    case IL2CPP_TYPE_R4:
        return "float";
    case IL2CPP_TYPE_R8:
        return "double";
    case IL2CPP_TYPE_I:
        return "intptr_t";
    case IL2CPP_TYPE_U:
        return "uintptr_t";

    case IL2CPP_TYPE_VALUETYPE: {
        *is_value_type = true;
        *is_custom_type = true;
        auto klass = il2cpp_class_from_type ? il2cpp_class_from_type(type) : nullptr;
        if (klass && il2cpp_class_is_enum && il2cpp_class_is_enum(klass)) {
            // Enum → use underlying type
            *is_value_type = false;
            *is_custom_type = false;
            auto base_type = il2cpp_class_enum_basetype ? il2cpp_class_enum_basetype(klass) : nullptr;
            if (base_type) {
                return get_field_type_name(base_type, is_value_type, is_custom_type);
            }
            return "int32_t";
        }
        auto ns = il2cpp_class_get_namespace ? il2cpp_class_get_namespace(klass) : "";
        auto cn = il2cpp_class_get_name ? il2cpp_class_get_name(klass) : "";
        std::string full = (ns && ns[0]) ? (std::string(ns) + "_" + std::string(cn)) : std::string(cn);
        return fix_name(full.c_str()) + "_o";
    }

    case IL2CPP_TYPE_STRING:
        *is_custom_type = true;
        return "System_String_o*";

    case IL2CPP_TYPE_PTR: {
        // Pointer type: element_type*
        // The data.type field points to the element type
        // For simplicity, treat as void*
        return "void*";
    }

    case IL2CPP_TYPE_CLASS:
    case IL2CPP_TYPE_OBJECT: {
        *is_custom_type = true;
        auto klass = il2cpp_class_from_type ? il2cpp_class_from_type(type) : nullptr;
        if (klass) {
            auto ns = il2cpp_class_get_namespace ? il2cpp_class_get_namespace(klass) : "";
            auto cn = il2cpp_class_get_name ? il2cpp_class_get_name(klass) : "";
            std::string full = (ns && ns[0]) ? (std::string(ns) + "_" + std::string(cn)) : std::string(cn);
            return fix_name(full.c_str()) + "_o*";
        }
        return "Il2CppObject*";
    }

    case IL2CPP_TYPE_SZARRAY:
    case IL2CPP_TYPE_ARRAY: {
        *is_custom_type = true;
        // Get element class name for array type name
        auto klass = il2cpp_class_from_type ? il2cpp_class_from_type(type) : nullptr;
        if (klass) {
            auto elem = il2cpp_class_get_element_class ? il2cpp_class_get_element_class(klass) : nullptr;
            if (elem) {
                auto ns = il2cpp_class_get_namespace ? il2cpp_class_get_namespace(elem) : "";
                auto cn = il2cpp_class_get_name ? il2cpp_class_get_name(elem) : "";
                std::string full = (ns && ns[0]) ? (std::string(ns) + "_" + std::string(cn)) : std::string(cn);
                return fix_name(full.c_str()) + "_array*";
            }
        }
        return "Il2CppObject_array*";
    }

    case IL2CPP_TYPE_GENERICINST: {
        // Generic instance type
        *is_custom_type = true;
        auto klass = il2cpp_class_from_type ? il2cpp_class_from_type(type) : nullptr;
        if (klass) {
            // Check if it's a value type generic
            bool is_vt = il2cpp_class_is_valuetype ? il2cpp_class_is_valuetype(klass) : false;
            bool is_en = il2cpp_class_is_enum ? il2cpp_class_is_enum(klass) : false;

            if (is_en) {
                *is_value_type = false;
                *is_custom_type = false;
                auto base_type = il2cpp_class_enum_basetype ? il2cpp_class_enum_basetype(klass) : nullptr;
                if (base_type) {
                    return get_field_type_name(base_type, is_value_type, is_custom_type);
                }
                return "int32_t";
            }

            if (is_vt) {
                *is_value_type = true;
            }

            auto ns = il2cpp_class_get_namespace ? il2cpp_class_get_namespace(klass) : "";
            auto cn = il2cpp_class_get_name ? il2cpp_class_get_name(klass) : "";
            std::string full = (ns && ns[0]) ? (std::string(ns) + "_" + std::string(cn)) : std::string(cn);
            std::string name = fix_name(full.c_str());

            // For generic types, the class name often includes backtick+arity (e.g. List`1)
            // We need to include generic arguments in the name
            // For now, use the class name as-is (it may contain generic arity markers)
            if (is_vt) {
                return name + "_o";
            }
            return name + "_o*";
        }
        return "Il2CppObject*";
    }

    case IL2CPP_TYPE_VAR:
    case IL2CPP_TYPE_MVAR:
        // Generic parameter — treat as Il2CppObject*
        *is_custom_type = true;
        return "Il2CppObject*";

    case IL2CPP_TYPE_BYREF: {
        // byref = pointer to the element type
        // The Il2CppType for byref has the underlying type in data
        // For simplicity, treat as void*
        *is_custom_type = false;
        return "void*";
    }

    case IL2CPP_TYPE_FNPTR:
        return "void*";

    default:
        return "void";
    }
}

std::vector<StructInfo> collect_type_info() {
    std::vector<StructInfo> result;

    if (!il2cpp_domain_get || !il2cpp_domain_get_assemblies ||
        !il2cpp_assembly_get_image || !il2cpp_image_get_class_count ||
        !il2cpp_image_get_class) {
        LOGE("collect_type_info: required API functions not available");
        return result;
    }

    auto domain = il2cpp_domain_get();
    if (!domain) return result;

    size_t asm_count = 0;
    auto assemblies = il2cpp_domain_get_assemblies(domain, &asm_count);
    if (!assemblies || asm_count == 0) return result;

    for (size_t i = 0; i < asm_count; i++) {
        auto image = il2cpp_assembly_get_image(assemblies[i]);
        if (!image) continue;
        auto class_count = il2cpp_image_get_class_count(image);

        for (size_t j = 0; j < class_count; j++) {
            auto klass = const_cast<Il2CppClass *>(il2cpp_image_get_class(image, j));
            if (!klass) continue;

            StructInfo si;
            auto ns = il2cpp_class_get_namespace ? il2cpp_class_get_namespace(klass) : "";
            auto cn = il2cpp_class_get_name ? il2cpp_class_get_name(klass) : "";

            // Build full type name
            std::string full;
            if (ns && ns[0]) {
                full = std::string(ns) + "_" + std::string(cn);
            } else {
                full = std::string(cn);
            }
            si.type_name = fix_name(full.c_str());

            si.is_value_type = il2cpp_class_is_valuetype ? il2cpp_class_is_valuetype(klass) : false;
            si.is_enum = il2cpp_class_is_enum ? il2cpp_class_is_enum(klass) : false;

            // Parent class
            auto parent = il2cpp_class_get_parent ? il2cpp_class_get_parent(klass) : nullptr;
            if (parent) {
                auto pns = il2cpp_class_get_namespace ? il2cpp_class_get_namespace(parent) : "";
                auto pcn = il2cpp_class_get_name ? il2cpp_class_get_name(parent) : "";
                std::string pfull;
                if (pns && pns[0]) {
                    pfull = std::string(pns) + "_" + std::string(pcn);
                } else {
                    pfull = std::string(pcn);
                }
                si.parent_name = fix_name(pfull.c_str());
            }

            // Skip System.Object and System.ValueType as parent names
            // (they don't need _Fields inheritance)
            if (si.parent_name == "System_Object" || si.parent_name == "System_ValueType") {
                si.parent_name.clear();
            }

            // Collect instance and static fields
            if (il2cpp_class_get_fields && il2cpp_field_get_name && il2cpp_field_get_type) {
                void *field_iter = nullptr;
                std::set<std::string> used_names;

                while (auto field = il2cpp_class_get_fields(klass, &field_iter)) {
                    auto fname = il2cpp_field_get_name(field);
                    if (!fname) continue;

                    auto ftype = il2cpp_field_get_type(field);
                    if (!ftype) continue;

                    // Skip const (literal) fields
                    if ((ftype->attrs & FIELD_ATTRIBUTE_LITERAL) != 0) continue;

                    StructFieldInfo fi;
                    bool is_vt = false, is_custom = false;
                    fi.type_name = get_field_type_name(ftype, &is_vt, &is_custom);
                    fi.is_value_type = is_vt;
                    fi.is_custom_type = is_custom;

                    // Fix field name and handle duplicates
                    std::string fixed_name = fix_name(fname);
                    if (!used_names.insert(fixed_name).second) {
                        fixed_name = "_" + std::to_string(used_names.size()) + "_" + fixed_name;
                        used_names.insert(fixed_name);
                    }
                    fi.field_name = fixed_name;

                    // Check if static
                    if ((ftype->attrs & FIELD_ATTRIBUTE_STATIC) != 0) {
                        si.static_fields.push_back(fi);
                    } else {
                        si.fields.push_back(fi);
                    }
                }
            }

            result.push_back(si);
        }
    }

    LOGI("collect_type_info: collected %zu types", result.size());
    return result;
}

// ================================================================
// Pure logic — generate il2cpp.h content (unit-testable)
// ================================================================

std::string generate_il2cpp_h_content(const std::vector<StructInfo> &types) {
    std::ostringstream sb;

    // Build a set of all type names for dependency tracking
    std::set<std::string> all_type_names;
    for (const auto &t : types) {
        all_type_names.insert(t.type_name);
    }

    // Track which types have been emitted (for dependency ordering)
    std::set<std::string> emitted;

    // Forward declarations
    sb << "// Forward declarations\n";
    for (const auto &t : types) {
        sb << "struct " << t.type_name << "_Fields;\n";
        sb << "struct " << t.type_name << "_o;\n";
        sb << "struct " << t.type_name << "_c;\n";
        if (t.has_static_fields()) {
            sb << "struct " << t.type_name << "_StaticFields;\n";
        }
    }
    sb << "\n";

    // Helper: emit a type and its dependencies first
    // We use a simple recursive approach with cycle detection
    std::function<void(const StructInfo &, std::ostringstream &)> emit_struct;
    emit_struct = [&](const StructInfo &info, std::ostringstream &out) {
        if (emitted.count(info.type_name)) return;

        // Emit parent first if it exists and is in our type set
        if (!info.parent_name.empty() && all_type_names.count(info.parent_name)) {
            // Find parent StructInfo
            for (const auto &t : types) {
                if (t.type_name == info.parent_name) {
                    emit_struct(t, out);
                    break;
                }
            }
        }

        // Emit field dependencies (value types that are embedded)
        for (const auto &f : info.fields) {
            if (f.is_value_type && f.is_custom_type) {
                // Extract the type name from the field type (strip "_o" suffix)
                std::string dep_name = f.type_name;
                if (dep_name.size() > 2 && dep_name.substr(dep_name.size() - 2) == "_o") {
                    dep_name = dep_name.substr(0, dep_name.size() - 2);
                }
                if (all_type_names.count(dep_name) && !emitted.count(dep_name)) {
                    for (const auto &t : types) {
                        if (t.type_name == dep_name) {
                            emit_struct(t, out);
                            break;
                        }
                    }
                }
            }
        }

        // Skip enum types — they use their underlying type directly
        if (info.is_enum) {
            emitted.insert(info.type_name);
            return;
        }

        // --- _Fields struct ---
        out << "struct " << info.type_name << "_Fields";
        if (!info.parent_name.empty() && all_type_names.count(info.parent_name)) {
            out << " : " << info.parent_name << "_Fields";
        }
        out << " {\n";
        for (const auto &f : info.fields) {
            if (f.is_custom_type) {
                out << "\tstruct " << f.type_name << " " << f.field_name << ";\n";
            } else {
                out << "\t" << f.type_name << " " << f.field_name << ";\n";
            }
        }
        if (info.fields.empty() && info.parent_name.empty()) {
            // Empty struct — add a dummy field to avoid zero-size struct
            out << "\tuint8_t __dummy;\n";
        }
        out << "};\n\n";

        // --- _StaticFields struct (if has static fields) ---
        if (info.has_static_fields()) {
            out << "struct " << info.type_name << "_StaticFields {\n";
            for (const auto &f : info.static_fields) {
                if (f.is_custom_type) {
                    out << "\tstruct " << f.type_name << " " << f.field_name << ";\n";
                } else {
                    out << "\t" << f.type_name << " " << f.field_name << ";\n";
                }
            }
            out << "};\n\n";
        }

        // --- _c struct (class metadata) ---
        out << "struct " << info.type_name << "_c {\n";
        out << "\tIl2CppClass_1 _1;\n";
        if (info.has_static_fields()) {
            out << "\tstruct " << info.type_name << "_StaticFields* static_fields;\n";
        } else {
            out << "\tvoid* static_fields;\n";
        }
        out << "\tconst Il2CppRGCTXData* rgctx_data;\n";
        out << "\tIl2CppClass_2 _2;\n";
        out << "};\n\n";

        // --- _o struct (object instance) ---
        out << "struct " << info.type_name << "_o {\n";
        if (!info.is_value_type) {
            out << "\t" << info.type_name << "_c *klass;\n";
            out << "\tvoid *monitor;\n";
        }
        out << "\t" << info.type_name << "_Fields fields;\n";
        out << "};\n\n";

        emitted.insert(info.type_name);
    };

    // Emit all type structs in dependency order
    sb << "// Type definitions\n\n";
    for (const auto &t : types) {
        emit_struct(t, sb);
    }

    // --- Array type structs ---
    sb << "// Array type definitions\n\n";
    std::set<std::string> emitted_arrays;
    for (const auto &t : types) {
        if (t.is_enum) continue;
        std::string arr_name = t.type_name + "_array";
        if (emitted_arrays.count(arr_name)) continue;
        emitted_arrays.insert(arr_name);

        sb << "struct " << arr_name << " {\n";
        sb << "\tIl2CppObject obj;\n";
        sb << "\tIl2CppArrayBounds *bounds;\n";
        sb << "\til2cpp_array_size_t max_length;\n";
        if (t.is_value_type) {
            sb << "\t" << t.type_name << "_o m_Items[65535];\n";
        } else {
            sb << "\t" << t.type_name << "_o* m_Items[65535];\n";
        }
        sb << "};\n\n";
    }

    return sb.str();
}

// ================================================================
// I/O — write il2cpp.h to disk
// ================================================================

void write_il2cpp_h(const char *outDir, const std::vector<StructInfo> &types) {
    auto outPath = std::string(outDir).append("/files/il2cpp.h");
    LOGI("writing il2cpp.h to %s", outPath.c_str());

    std::ofstream f(outPath);
    if (!f.is_open()) {
        LOGE("failed to create %s", outPath.c_str());
        return;
    }

    f << kGenericHeader;
    f << kVersionHeader;
    f << generate_il2cpp_h_content(types);

    f.close();
    LOGI("il2cpp.h done! %zu types", types.size());
}
