name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of the game:"
          required: true
          default: "com.wxlhs6.dmlt.gz01"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: sdkmanager --install "ndk;25.2.9519653"

    - name: Apply package name
      run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h

    - name: Build
      run: ./gradlew :module:assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper
        path: out/magisk_module_release/
